### ISSUE TITLE
"date modified" needs to be added

### ISSUE THREAD

**Issue by stef-barburou** [DIS-SIN/Busrides#128]
Date modified is missing from your page templates as a required element.

![image](https://user-images.githubusercontent.com/41083520/150801916-3dd63b70-c011-4077-a4fd-0301c47fe577.png)

**Comment by stef-barburou** [comment]
is there a way to automate this?

**Comment by stef-barburou** [comment]
@kroussea @romy-piche 
Do you guys know if it's possible for react to update this automatically ?

**Comment by romy-piche** [comment]
Good question ! Since the content come from the ghost API, I guess that if we are on an episode, it would be the last update from the episode ? If so that could be from the ghost API: https://ghost.org/docs/content-api/#posts (_update_at_ field)
For the home page however, I don't know what 'date' could be used however.
