### ISSUE TITLE
learning paths uses different body font

### ISSUE THREAD

**Issue by stef-barburou** [DIS-SIN/Busrides#144]
. This page uses a different body font that your other pages. There may be others.
https://busrides-trajetsenbus.csps-efpc.gc.ca/en/learning-paths

**Comment by stef-barburou** [comment]
root body font-familly
![image](https://user-images.githubusercontent.com/41083520/150990636-d73b2670-6c58-43d4-ae81-5012b2811b0e.png)

learning path body font-familly
![image](https://user-images.githubusercontent.com/41083520/150990737-3a638ace-8ddc-4aa3-b35a-75f94fe19d52.png)

**Comment by romy-piche** [comment]
Maybe it is not the font ? Because the font is the same, but the size is different compared to an episode content / post content (ex: https://busrides-trajetsenbus.csps-efpc.gc.ca/en/en-about for the `<p>` element)
![image](https://user-images.githubusercontent.com/82387465/151047488-b2fc8b48-4bf3-4420-bfb6-dacd0176eccc.png)
![image](https://user-images.githubusercontent.com/82387465/151047569-cf753cfd-7227-4177-9d7e-7e4969181a43.png)

**Comment by stef-barburou** [comment]
fair enough, normal content seems to be 18px. so should probably change learning path computer font to 18px

**Comment by stef-barburou** [comment]
@kroussea le 14rem dans styles.css, c'Est basé sur quelque chose ? toutes les pages sauf learning path, le font est à 1.8 pis quand je plug ç aà 1.8, ça SEMBLE régler mon bobo mais jsais pas si ça fuck pas dequoi d'autre
`
/* GCWeb theme fix */
p {
    font-size: 1.4rem;
    margin: revert;
}
`

**Comment by kroussea** [comment]
> 

rem c'Est basé sur le font-size de l'élement root (html). Essentiellement c'est du sizing relatif.
Je sais pas c'est quoi l'issue au juste, mais quand j'ai droppé le GCTheme dans busrides, j'ai du adapter les font-sizes partout vu que la font-family avait changé. (increase)
So probable que de le monter a 1.8 fixerait le dit problème, faudrait voir dans un PR.
