### ISSUE TITLE
Twitter Card issue

### ISSUE THREAD

**Issue by stef-barburou** [DIS-SIN/Busrides#184]
twitter preview card for https://busrides-trajetsenbus.csps-efpc.gc.ca/ is showing up blank. Vanessa has updated the meta-data on Ghost, We used to have this issues before migration, but was fixed. Not sure if it's something that needs to be updated on the back end.

(https://cards-dev.twitter.com/validator)

**Comment by romy-piche** [comment]
I think the issue is because the path is relative, but twitter needs the full url. It seems to have been fixed here:
https://github.com/DIS-SIN/Busrides/commit/c87779506867318ce5529c3ea671dd363aa9e260

But the home page and search result uses the relative path for the image since there: https://github.com/DIS-SIN/Busrides/commit/5caef0ce006cf16c5ad9ff50058f39664036657a

(ex: The twitter card for an episode still work https://busrides-trajetsenbus.csps-efpc.gc.ca/en/ep-82-en)

**Comment by romy-piche** [comment]
Now working according to the validator (https://cards-dev.twitter.com/validator)
